data_params:
    need_normalize: True
    mat_file: 'DC_motor_simulation/res.mat'
    leave_nth: 13 #KD: choosing simple value to avoid systematic error
    test_size: 0.3
    use_part_of_data: 0.3
network_params:
    #input_size: 128
    input_size: 64
    retrospective_steps: 128
# If `per_element` is True, then LSTM reads in one timestep at a time.
    per_element: True
# size of hidden layers
    hidden_size: 16
    output_dim: 3
    num_layers: 2
    dtype: torch.float
train_params:
    learning_rate: 0.001
    num_epochs: 15
    batch_size: 1024
    loss_fn: mse
    reduction: sum
    optimizer: adam
exp_path: "only_batches"
is_debug: False
to_generate_data: False
generator_params:
    a: 0.5
    b: 1.0
    f_X: "math.sin"
    f_Y: "math.cos"
        