data_params:
    need_normalize: True
    mat_file: 'DC_motor_simulation/res.mat'
    leave_nth: 13 #KD: choosing simple value to avoid systematic error
    integration_step: 0.01
    test_size: 0.3
    use_part_of_data: 1.0
network_params:
    #input_size: 128
    input_size: 64
    retrospective_steps: 64
# If `per_element` is True, then LSTM reads in one timestep at a time.
    per_element: True
# size of hidden layers
    hidden_size: 8
    output_dim: 3
    num_layers: 1
    dtype: torch.float
train_params:
    optimizer:
        loss_fn: mse
        reduction: sum
        optimizer: adam
        weight_decay: 0
        learning_rate: 0.01
    lr_scheduler:
        early_stop_order: -7
        threshold: 0.05
        lr_drop: 0.3
        patience: 2
        cooldown: 3
    
    auto_loss: True
    
    
    
    num_epochs: 150
    batch_size: 256
    
    core_loss:
        part_of_max_for_const: 0.2
        scaling_order: 5
    aux_loss:
        part_of_max_for_const: 0.25
        scaling_order: 7
        steady_state_threshold: 0.001
exp_path: "only_batches"
is_debug: False
to_generate_data: False
generator_params:
    a: 0.5
    b: 1.0
    f_X: "math.sin"
    f_Y: "math.cos"
        